### ISSUE TITLE
🐞 Tab buttons should use pointer cursor

### ISSUE THREAD

**Issue by unrealsolver** [iTechLibrary/mimir#333]
- Environment: https://mimirapp.xyz/readers/11
- Client: FF

### ✔️ Expected behavior
When I put a cursor over a tab button (All items / Overdue) cursor should became a pointer :point_up_2: 

### ✖️ Actual behavior
Cursor is showing up as an `I` shape instead

### Screenshot / Descriptions
![mimir-pointer](https://user-images.githubusercontent.com/1101771/183924905-12cef4e9-5097-4bf8-9152-d925298bda49.png)

**Comment by unrealsolver** [comment]
QA on prod failed

**Comment by x8er** [comment]
> QA on prod failed

It fails on any github actions because of issues in ozby.service
