### ISSUE TITLE
Drop downs should work and match UI Kit

### ISSUE THREAD

**Issue by unrealsolver** [iTechLibrary/mimir#400]
[Figma](https://www.figma.com/file/pxj9Hhk5AdOxXWJP0dq4gT/Library-App-Spec?node-id=4605%3A9469)
 
![image](https://user-images.githubusercontent.com/1101771/189755167-71728361-391f-486f-9062-02be5f7c8d35.png)

**Comment by sabrina34352** [comment]
this was solved in last PR by me


![Image](https://user-images.githubusercontent.com/63979168/190326765-84b83683-53e0-4aee-b248-130177b28790.png)
