### ISSUE TITLE
🐞:exclamation: Clicking on the card should navigate to card details

### ISSUE THREAD

**Issue by unrealsolver** [iTechLibrary/mimir#445]
- Environment: https://mimirapp.xyz/books-stuff
- Client: FF

### ✔️ Expected behavior
Item details page should be opened
![image](https://user-images.githubusercontent.com/1101771/195066075-124ff83f-339b-4872-971f-b7c380a8d2af.png)

### ✖️ Actual behavior
Item history page opened: https://mimirapp.xyz/item/12
![image](https://user-images.githubusercontent.com/1101771/195065562-d0182c0c-e385-484a-bc94-d0aaea300b3b.png)

### Screenshot / Descriptions
![image](https://user-images.githubusercontent.com/1101771/195065331-cdd9d70a-b281-4e7a-897c-64921808506d.png)

**Comment by IvanUglovets** [comment]
locally everything works, it's not entirely clear why this error is thrown

**Comment by unrealsolver** [comment]
All migrations are applied:
![image](https://user-images.githubusercontent.com/1101771/195082260-7c22ece9-1f4a-467e-9204-c04ab8e6e37b.png)

**Comment by unrealsolver** [comment]
Okay, I restarted the server and it gone. I think I forget to restart it after deploy :man_facepalming: , sorry for the false alarm
