### ISSUE TITLE
:iphone: Adjust user login page

### ISSUE THREAD

**Issue by Chichmarin17** [iTechLibrary/mimir#458]
### How it should look 
![Main_hello](https://user-images.githubusercontent.com/73520274/197971068-4224fb4a-f9bb-4fff-a073-bbda0205483f.png)

### How it looks like
![image](https://user-images.githubusercontent.com/73520274/197971149-96be0c3c-7b8d-449d-a4b3-e4dbb111f41f.png)
![image](https://user-images.githubusercontent.com/73520274/197971305-2c69cadc-900a-49b9-a014-f1fc8f1a62eb.png)

### Notes
If there is no user in database, currently we shows the user the next view with `Enter your current location`. This should be done as at the first screenshot i.e. the selection of a location should be appeared on the first page if the user logs in the first time

### Figma design
https://www.figma.com/file/pxj9Hhk5AdOxXWJP0dq4gT/Library-App-Spec?node-id=1091%3A4824

Please, also note that the current mobile version of the login page doesn't fit the width of the display on mobile i.e. there should be `no horizontal scrollbar`

**Comment by mabrur-h** [comment]
It seems it's impossible to do this task. I can not identify if a user exists in our database before signing in.

**Comment by Chichmarin17** [comment]
@mabrur-h could you at least adjust this page to match mobile ui? I mean remove horizontal scrolling at least

**Comment by mabrur-h** [comment]
@Chichmarin17 Can you please check it one more time, because I can't see scrolling on my device and computer? 
If I'm not mistaken, I fixed it on task #461.

**Comment by mabrur-h** [comment]
![image](https://user-images.githubusercontent.com/52496254/202923858-54404df2-d709-4482-875e-35873d89bcb0.png)

I think it was fixed after the last merge

**Comment by Chichmarin17** [comment]
Close the issue as it can't be implemented with the current backend
