### ISSUE TITLE
:iphone: Adjust user search page with filters

### ISSUE THREAD

**Issue by Chichmarin17** [iTechLibrary/mimir#467]
### How it should look:
![Results](https://user-images.githubusercontent.com/73520274/199187891-04f4dc66-cd97-47fc-ab0d-b9f060693222.png)

### How it looks like
![image](https://user-images.githubusercontent.com/73520274/199187598-11357c3b-3850-4c6e-9744-8bab2fcb71d0.png)

### Figma design
https://www.figma.com/file/pxj9Hhk5AdOxXWJP0dq4gT/Library-App-Spec?node-id=4993%3A15165

**Comment by mabrur-h** [comment]
Close #467
![image](https://user-images.githubusercontent.com/52496254/200173159-b5168a64-f403-40fd-a6b8-f1c77f4f5fc7.png)
![image](https://user-images.githubusercontent.com/52496254/200173179-094efa47-4174-4e78-ada9-625abb07396b.png)
