### ISSUE TITLE
Cannot access donates from user page🐞 

### ISSUE THREAD

**Issue by sabrina34352** [iTechLibrary/mimir#475]
- Environment: mimirapp.xyz
- Client:
it works fine on localhost, but on prod something goes wrong
### ✔️ Expected behavior

How it should work
![image](https://user-images.githubusercontent.com/63979168/199716230-79edb749-efa4-43ee-b579-2a993de89741.png)

### ✖️ Actual behavior

How it works now
![image](https://user-images.githubusercontent.com/63979168/199716175-6b246251-1ff0-46a6-97fe-bed7dcda0c36.png)

**Comment by Chichmarin17** [comment]
There was a donated material issue. The issue will be closed as it can not be reproduce atm
