### ISSUE TITLE
🖥 Adjust donates from user search UI

### ISSUE THREAD

**Issue by mabrur-h** [iTechLibrary/mimir#495]
**How it should look:**
![image](https://user-images.githubusercontent.com/52496254/201858083-1ea36262-6418-45e0-9504-8236d8f68d7a.png)

**How it looks like:**
![image](https://user-images.githubusercontent.com/52496254/201857425-bc3ffbfa-c06f-492e-906a-f957452b7b84.png)

**Figma Design**
https://www.figma.com/file/pxj9Hhk5AdOxXWJP0dq4gT/Library-App-Spec?node-id=1206%3A5934&t=JuWv9qcnRJiC49Zu-0

**Comment by Chichmarin17** [comment]
We should wait until Ekaterina finishes with the mobile design for that page. But yeah, we definitely should do that in the nearest future
