### ISSUE TITLE
🐞 Placeholder text in the Search bar doesn't change immediately after language change

### ISSUE THREAD

**Issue by Chichmarin17** [iTechLibrary/mimir#501]
- Environment: https://mimirapp.xyz/settings
- Client:

### ✔️ Expected behavior

How it should work
Should change the placeholder right after switching to a new language

### ✖️ Actual behavior

How it works now
It doesn't change it's value until you navigate to a different url

### Screenshot / Descriptions
![image](https://user-images.githubusercontent.com/73520274/202135735-56892688-8fc1-4ff8-bb66-92b3ed1a61b6.png)

**Comment by sabrina34352** [comment]
closed in pr #508
