### ISSUE TITLE
Locations repeat twice in settings page🐞 

### ISSUE THREAD

**Issue by sabrina34352** [iTechLibrary/mimir#507]
- Environment: mimirapp.xyz
- Client: FE

### ✔️ Expected behavior

How it should work

### ✖️ Actual behavior

How it works now
![image](https://user-images.githubusercontent.com/63979168/202664697-9616510b-ff56-41b0-8a1e-e92d3a8843ad.png)

**Comment by Chichmarin17** [comment]
Provide some info how to replicate the issue cause I can't see it
![image](https://user-images.githubusercontent.com/73520274/202668043-bcc46ea5-5f3d-4874-a945-f5c3d10d0d42.png)

**Comment by sabrina34352** [comment]
> @sabrina34352 Provide some info how to replicate the issue cause I can't see it ![image](https://user-images.githubusercontent.com/73520274/202668043-bcc46ea5-5f3d-4874-a945-f5c3d10d0d42.png)

it was a problem on my localhost i wasnt attentive :(
